version: "3.9"
services:
  it-tools:
    image: corentinth/it-tools
    container_name: clockworks-it-tools
    volumes:
      - "config:/config/"
    network_mode: bridge
    ports:
      - "5546:80"
    environment:
      - TZ=Europe/Bucharest
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://it-tools.clockworks.ro/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

volumes:
  config:
